The-Fellowship-of-the-stRing/project-atelier

client/src/App.jsx
=> branch test

client/src/App.jsx
testing how to do change in branch and then pull request
=> test change to App.jsx

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Related.jsx, client/src/containers/RelatedOutfits.jsx, client/src/stylesheets/related_outfits/relatedOutfits.css, client/src/utils/getCardData.js
@gordon1213 @kssampson Please review!
=> Re-added useEffect to related

README.md, client/src/components/ratings_review/ReviewList.jsx, client/src/components/related_outfits/Card.jsx, client/src/components/stars/Stars.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/containers/RatingsReviews.jsx, client/src/utils/getCardData.js, client/src/utils/getReviews.js
added api call for reviews and fixed react syntax
=> Dropdown api call

client/src/App.jsx, client/src/components/ratings_review/NumberReviews.jsx, client/src/components/ratings_review/ReviewList.jsx, client/src/components/ratings_review/ReviewTile.jsx, client/src/components/ratings_review/SortDropDown.jsx, client/src/components/ratings_review/Stars.jsx, client/src/stylesheets/ratings_review/ratingsReview.css, client/src/stylesheets/ratings_review/reviewList.css, client/src/stylesheets/ratings_review/reviewTile.css, client/src/stylesheets/ratings_review/sortDropDown.css, client/src/stylesheets/stars/stars.css, client/src/utils/getFirstItem.js, client/src/utils/getReviews.js
1. Added drop down list sorting to render 2 reviews but store 10 values
2. Added more reviews button to render more views per click
3. Button will be hidden when at max reviews
4. Added total reviews count display
5. Added total "yes" count
6. Added minor styling to include scrolling view to prevent increased page length
@gordon1213 @kssampson @clee4037 please review and approve at your earliest.
when this is completed and merged don't forget to commit and then execute a pull request to get latest from the main branch.
=> Created Review List component sorting, display, and more button functions

client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx
Container:
- API call for question data updated to include sorting/filtering
- added new state, resultsToShow, to hold sorted/filtered data
- add currentCount state and click handler to manage More Answered Questions button
QuestionsList
- started map through resultsToShow
- created Answers component to work with additional answer data
Answers
- new component
=> Questions list

client/src/App.jsx, client/src/components/ratings_review/ReviewList.jsx, client/src/components/ratings_review/ReviewTile.jsx, client/src/styles.css, client/src/stylesheets/ratings_review/reviewList.css, client/src/stylesheets/ratings_review/reviewTile.css, client/src/utils/markHelpful.js, client/src/utils/reportReview.js
Review List component is built out per specs of BRD.
Additionally I added a spinner loader on our main component
Please review and approve to merge @gordon1213 @kssampson @clee4037
=> Completed build for Review List Component

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Related.jsx, client/src/stylesheets/related_outfits/relatedOutfits.css, client/src/utils/getCardData.js
@gordon1213 @kssampson Please review!
=> Ro card layout

client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/answers.css, client/src/stylesheets/questions_answers/questionsAnswers.css, client/src/stylesheets/questions_answers/questionsList.css
- created answers.css
- updated name of questionsList css file
- added stylings to questionsList, Answers component elements
- made small changes inline in components
=> CSS updates

client/src/components/ratings_review/AddFormStars.jsx, client/src/components/ratings_review/AddReview.jsx, client/src/components/ratings_review/ReviewTile.jsx, client/src/stylesheets/ratings_review/addReview.css
1. Overlay for modal
2. Modal with close method applied
3. Form started
4. Added overall rating with star click functionality
5. Added radio buttons for recommending product
Please review at your earliest @gordon1213 @kssampson @clee4037
=> Add review form

client/src/App.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/ratings_review/AddReview.jsx, client/src/components/ratings_review/ReviewList.jsx, client/src/containers/RatingsReviews.jsx, client/src/stylesheets/ratings_review/addReview.css
Completed categories functionality
=> Add form categories

client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx
- added functionality to QuestionsList Questions Yes count
=> added yes functionality to Questions in QuestionsList component

client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx
- added yes functionality to answers component
=> Answers yes reported

client/src/components/ratings_review/AddReview.jsx, client/src/utils/addReview.js, client/src/utils/getFirstItem.js, client/src/utils/getItemDetails.js, client/src/utils/getReviewMeta.js, client/src/utils/getReviews.js, client/src/utils/markHelpful.js, client/src/utils/reportReview.js, package-lock.json, package.json, server.js, webpack.config.js
added server to handle api requests
=> Server handler

client/src/components/questions_answers/Answers.jsx, client/src/containers/QuestionsAnswers.jsx
=> changed endpoints

client/src/components/product_details/Cart.jsx, client/src/components/product_details/ExpandedView.jsx, client/src/components/product_details/ImageGallery.jsx, client/src/components/product_details/Reviews.jsx, client/src/components/product_details/SocialMedia.jsx, client/src/components/product_details/StyleList.jsx, client/src/containers/ProductDetails.jsx, client/src/stylesheets/product_details/productDetails.css, client/src/stylesheets/product_details/styleList.css
Added images for style selector
=> Product details style (Look at this one second)

client/src/App.jsx, client/src/components/ratings_review/RatingFactors.jsx, client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/components/related_outfits/Related.jsx, client/src/containers/RelatedOutfits.jsx
@LukeLarson2 I have notes for you on RatingFactors.jsx. 
- Rendering the entire page for certain products isn't working. I think the issue is that many products don't have all of the data/info required in your rating factors component.
=> Update Main Product 

client/src/components/questions_answers/AddAnswer.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/AddAnswerModal.css, client/src/stylesheets/questions_answers/questionsAnswers.css, package.json
- several small changes to make components more readable
- built AddAnswer modal component
- built out AddAnswerModal.css for the new component
- fleshed out form and state for the component
- passed around different props to try and get the data I need for the new component
=> Added AddAnswer modal w/ css component

client/src/components/ratings_review/ReviewList.jsx, client/src/components/ratings_review/StarBar.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/stylesheets/ratings_review/reviewList.css, package-lock.json, package.json, tests/rating-review.test.jsx, tests/test.data.js, webpack.config.js
Added two test files for ratings and reviews, largest chuck comes form package-lock.json
=> Review tests

client/src/App.jsx, client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/components/related_outfits/Related.jsx, client/src/containers/RelatedOutfits.jsx
@clee4037 @gordon1213 @LukeLarson2  Please review!
- Refactor add and delete outfit handlers
- Refactor update main product handler
=> Click Handlers

client/src/components/questions_answers/AddAnswer.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/questionsAnswers.css
- Fixed missing Reported functionality lost in previous push
- Have put & get for Add Answer component
=> Add answer update

client/src/components/questions_answers/AddAnswer.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx
- now getting answers unique to each question for Add Answer feature
- still wanting to show without needing refresh, but not part of BMR
- started adding state for Search
=> Fix same a for every q

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/stylesheets/related_outfits/CompareModal.css, client/src/stylesheets/related_outfits/relatedOutfits.css
=> Add scroll functionality and update card styling

client/src/components/questions_answers/AddQuestion.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/AddQuestionModal.css
- made AddQuestion component
- made related css file
- implemented modal logic similar to AddAnswer in QuestionsAnswers container
- made state for the modal
=> AddQuestion component and AddQuestion.css implemented

client/src/components/ratings_review/AddReview.jsx, client/src/components/ratings_review/RatingFactors.jsx, tests/rating-review.test.jsx
Added 4 more tests to add rating modal
=> Add more tests

client/src/components/questions_answers/AddAnswer.jsx, client/src/components/questions_answers/AddQuestion.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/AddAnswerModal.css, client/src/stylesheets/questions_answers/AddQuestionModal.css
- gave functionality to Load More Answers feature
- still rendering all answers for all questions, but enough work done to push it up, continuing tomorrow
- added some css
=> Implemented Load More Answers

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Compare.jsx, client/src/stylesheets/related_outfits/CompareModal.css, client/src/stylesheets/related_outfits/relatedOutfits.css, client/src/stylesheets/stars/stars.css
=> Update compare format and styling

client/src/components/questions_answers/AddQuestion.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/AddAnswerModal.css, client/src/stylesheets/questions_answers/questionsList.css
- added placeholders, etc. in form
- validation function and related state
=> Qa cleanup

client/src/App.jsx, client/src/components/product_details/Reviews.jsx, client/src/containers/ProductDetails.jsx, client/src/containers/RatingsReviews.jsx, client/src/stylesheets/product_details/reviews.css
@LukeLarson2  Needed to add an id tag to your container so that I could reference it in my anchor tag.
=> Completed Review Section Functionality 

client/src/components/product_details/Image.jsx, client/src/components/product_details/ImageGallery.jsx, client/src/components/product_details/ImageSelect.jsx, client/src/stylesheets/product_details/imageGallery.css
Added ClickHandlers, changed the Image select so that it overlays the main image, made thumbnails only render 7 at a time, made thumbnails highlight when they're selected.
=> Product details image2

.gitignore, client/src/components/ratings_review/AddReview.jsx, tests/initial.test.jsx, tests/rating-review.test.jsx
Added testing to meet 76% coverage for Ratings and Reviews
=> More testing

client/src/components/ratings_review/AddFormStars.jsx, client/src/components/ratings_review/AddReview.jsx, client/src/components/ratings_review/RatingBreakdown.jsx, client/src/components/ratings_review/RatingFactors.jsx, client/src/components/ratings_review/ReviewList.jsx, client/src/components/ratings_review/ReviewTile.jsx, client/src/components/ratings_review/StarBar.jsx, client/src/components/ratings_review/Stars.jsx, client/src/stylesheets/stars/stars.css
corrected all eslint errors for ratings reviews
=> Continued eslint changes

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Carousel.jsx, client/src/components/related_outfits/Compare.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/components/related_outfits/Related.jsx, client/src/containers/RelatedOutfits.jsx
=> Fixed all eslint issues

client/src/components/product_details/Image.jsx, client/src/components/product_details/ImageSelect.jsx, client/src/components/product_details/Style.jsx, client/src/containers/ProductDetails.jsx
Fixed Linting for all of product_details files made so far
=> Product details lint

client/src/components/product_details/ImageGallery.jsx, client/src/containers/ProductDetails.jsx, client/src/stylesheets/product_details/imageGallery.css, client/src/stylesheets/product_details/productDetails.css
Current Non-breaking code for Lauren to look at
=> Product details progress

client/src/components/questions_answers/AddQuestion.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx
- Adjusted for accessibility
- Continued work needed on layout issues due to change
=> Fix access

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Carousel.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/components/related_outfits/Stars.jsx, client/src/stylesheets/related_outfits/relatedOutfits.css
@gordon1213 @kssampson @LukeLarson2 Please review
=> Fixing Outfits Section

client/src/App.jsx, client/src/components/product_details/Reviews.jsx, client/src/containers/NavBar.jsx, client/src/containers/ProductDetails.jsx, client/src/styles.css, client/src/stylesheets/navbar/navbar.css, client/src/stylesheets/stars/stars.css, client/src/utils/handleRef.js, tests/product-details.test.jsx, tests/questions-answers.test.jsx, tests/related-outfits.test.jsx
added smooth scroll to top when clicking the app icon
made the ref handler dynamic for less dry code
=> Nav bar updates

client/src/components/ratings_review/ReviewList.jsx, client/src/styles.css, client/src/stylesheets/ratings_review/ratingsReview.css, client/src/stylesheets/ratings_review/reviewList.css, webpack.config.js
infinite scroll and additional styles added
=> integrated styling to match site and the infinite scroll

client/src/components/questions_answers/AddAnswer.jsx, client/src/components/questions_answers/Answers.jsx, client/src/components/questions_answers/QuestionsList.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/questionsAnswers.css
- decided not to move AddAnswer, found way around by adding state to QuestionsAnswers
- fixed bug which as result of AddAnswer changes, was rendering reported answers. Did so by adding filter in the fetch within Answers component
Note: Initially, I mistakenly worked in main. I did git reset --hard HEAD in main, then pulled from origin main, and merged in the moveAddAnswer branch. Please keep in mind when reviewing if you see any issues.
=> AddAnswer Changes

client/src/App.jsx, client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Carousel.jsx, client/src/components/related_outfits/Compare.jsx, client/src/components/related_outfits/Outfits.jsx, client/src/components/related_outfits/Related.jsx, client/src/containers/NavBar.jsx, client/src/containers/RelatedOutfits.jsx, client/src/stylesheets/related_outfits/CompareModal.css, client/src/stylesheets/related_outfits/relatedOutfits.css, client/src/utils/fetchManyCardData.js, client/src/utils/getRelatedItems.js, webpack.config.js
@gordon1213 @kssampson @LukeLarson2 Please review
=> Update compare styling and Finish rendering logic

client/src/components/questions_answers/Answers.jsx
- adjusted state updating in fetch in Answers
- moved filtering of reported status down into return statement
=> Fixed bug of reported answers still showing after load more answers

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Carousel.jsx, client/src/containers/RelatedOutfits.jsx, client/src/stylesheets/related_outfits/CompareModal.css, client/src/stylesheets/related_outfits/relatedOutfits.css
@gordon1213 @kssampson @LukeLarson2 Please review
=> Restyled Cards

client/src/components/product_details/ImageSelect.jsx, client/src/components/product_details/ImageSelectExpand.jsx
Implemented edge case of 0 photos and also removed console.log
=> Removed Console.log and fixed link logic

client/src/App.jsx, client/src/components/ratings_review/form/OverallRating.jsx, client/src/stylesheets/ratings_review/addReview.css
minor bug fixes and reset starting product
=> made bug corrections in ratings and reviews

client/src/components/questions_answers/QuestionsList.jsx, client/src/components/questions_answers/Search.jsx, client/src/containers/QuestionsAnswers.jsx, client/src/stylesheets/questions_answers/questionsAnswers.css
- added additional styling to searched text
- Conditionally rendered the questions and answers body based on if there are any questions, making it collapse if not
=> Presentation bugs

client/src/components/related_outfits/Card.jsx, client/src/components/related_outfits/Carousel.jsx, client/src/components/related_outfits/Compare.jsx, client/src/stylesheets/related_outfits/CompareModal.css, client/src/stylesheets/related_outfits/relatedOutfits.css
=> Updated card styling and fixed table hover bug

client/src/components/product_details/StyleList.jsx, client/src/components/related_outfits/Card.jsx, client/src/stylesheets/related_outfits/CompareModal.css, client/src/stylesheets/related_outfits/relatedOutfits.css, client/src/utils/fetchCardData.js
@gordon1213 @kssampson @LukeLarson2
=> Update colors and add image preview

client/src/components/navbar/Search.jsx, client/src/components/product_details/ExpandedView.jsx, client/src/components/product_details/Image.jsx, client/src/components/product_details/ImageExpand.jsx, client/src/components/product_details/ImageGallery.jsx, client/src/components/product_details/Reviews.jsx, client/src/components/product_details/Style.jsx, client/src/components/ratings_review/AddFormStars.jsx, client/src/components/ratings_review/RatingBreakdown.jsx, client/src/components/ratings_review/ReviewTile.jsx, client/src/components/ratings_review/StarBar.jsx, client/src/containers/NavBar.jsx, public/index.html
=> updated accessability
